# Generated by Django 4.1.4 on 2022-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='order_code',
        ),
        migrations.AddField(
            model_name='notebook',
            name='amount',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
