# Generated by Django 4.1.4 on 2022-12-16 08:57

import applications.notebook.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0002_notebook_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='owner',
            field=models.ForeignKey(default=applications.notebook.models.sup_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('notebook_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
