# Generated by Django 4.1.4 on 2022-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_remove_notebook_order_code_notebook_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
