# Generated by Django 4.1.4 on 2022-12-16 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0003_alter_notebook_owner_alter_notebook_price_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='notebook_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='notebook.notebook'),
        ),
        migrations.AlterField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notebook_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='notebook.notebook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
